config:
  test:
    ldap_username: jarvis
    ldap_password: password
  harbor:
    # NOTE(lamt): this url should include the scheme (http or https) and should
    # exclude trailing "/"
    api_url: https://harbor-harbor-core.harbor.svc.cluster.local
    admin_password: Harbor12345
  ldap:
    enabled: true
    data:
      auth_mode: ldap_auth
      ldap_base_dn: 'dc=jarvis,dc=local'
      ldap_search_dn: 'cn=readonly,dc=jarvis,dc=local'
      ldap_search_password: readonly
      ldap_uid: uid
      ldap_url: 'ldap://ldap-openldap.ldap.svc.cluster.local'
      ldap_group_membership_attribute: memberof
      ldap_group_attribute_name: cn
      ldap_group_admin_dn: 'cn=jarvis-admins,ou=Groups,dc=jarvis,dc=local'
      ldap_group_base_dn: 'ou=Groups,dc=jarvis,dc=local'
      # Scope values: 0=Base, 1=OneLevel, 2=Subtree
      ldap_scope: 2
      ldap_group_search_scope: 2
      ldap_verify_cert: false
      ldap_group_search_filter: "objectClass=groupOfUniqueNames"

params: {}

images:
  applications:
    harbor_ldap_job_init:
      name: kubernetes-entrypoint
      repo: quay.io/airshipit
      tag: v1.0.0
    harbor_ldap_job:
      name: curl
      repo: quay.io/stannum
      tag: 7.74.0
    harbor_ldap_test:
      name: curl
      repo: quay.io/stannum
      tag: 7.74.0
  pull:
    policy: IfNotPresent

over_rides: {}
