apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex-aio
  labels:
    app.kubernetes.io/name: dex-aio
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'