apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-aio
  labels:
    app.kubernetes.io/name: dex-aio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex-aio
subjects:
- kind: ServiceAccount
  name: dex-aio
  namespace: dex