apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dex-aio
  namespace: dex
  labels:
    app.kubernetes.io/name: dex-aio
rules:
- apiGroups:
  - dex.coreos.com
  resources:
  - authcodes
  - authrequests
  - connectors
  - oauth2clients
  - offlinesessionses
  - passwords
  - refreshtokens
  - signingkeies
  verbs:
  - '*'