apiVersion: v1
kind: Service
metadata:
  name: dex-aio
  namespace: dex
  labels:
    app.kubernetes.io/name: dex-aio
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 5554
    port: 5554
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 5556
    port: 5556
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: dex-aio