{{- define "secret-netrc" -}}
{{- $p := urlParse $.Values.config.test.grafana_uri -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: loki-netrc
data:
  good_ldap.rc: {{ b64enc ( printf "machine %s login %s password %s" $p.host $.Values.config.test.ldap_username $.Values.config.test.ldap_password ) }}
  bad_ldap.rc: {{ b64enc ( printf "machine %s login %s password %s" $p.host $.Values.config.test.ldap_username ( randAlphaNum 10 ) ) }}
{{- end -}}
{{- if (index $.Values "loki-stack" "grafana" "ldap" "enabled") }}
{{- include "helpers.template.overlay" (dict "Global" $ "template_definition" "secret-netrc") }}
{{- end }}
