apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dex
  name: dex-role-janedoe
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dex-rolebinding-janedoe
  namespace: dex
subjects:
- kind: User
  name: janedoe@example.com # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dex-role-janedoe
  apiGroup: rbac.authorization.k8s.io