{{- define "secret-harbor_ldap" -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: harbor-ldap-etc
data:
  config.json: {{ $.Values.config.ldap.data | toJson | b64enc }}
{{- end -}}
{{- if $.Values.config.ldap.enabled }}
{{- include "helpers.template.overlay" (dict "Global" $ "template_definition" "secret-harbor_ldap") }}
{{- end }}
