{{- define "secret-adminrc" -}}
{{- $p := urlParse $.Values.config.harbor.api_url -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: harbor-adminrc
data:
  admin.rc: {{ b64enc ( printf "machine %s login %s password %s" $p.host "admin" $.Values.config.harbor.admin_password ) }}
{{- end -}}
{{- if $.Values.config.ldap.enabled }}
{{- include "helpers.template.overlay" (dict "Global" $ "template_definition" "secret-adminrc") }}
{{- end }}
