{{- define "serviceaccount-harbor_ldap" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-ldap
  namespace: {{ $.Release.Namespace }}
{{- end -}}
{{- if $.Values.config.ldap.enabled }}
{{- include "helpers.template.overlay" (dict "Global" $ "template_definition" "serviceaccount-harbor_ldap") }}
{{- end }}
