{{- define "Certificate-dex" -}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "helpers.labels.fullname" . }}
  labels: {{- include "helpers.labels.labels" . | nindent 4 }}
spec:
  secretName: dex-aio-tls
  issuerRef:
    name: jarvis-kubernetes
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
  commonName: dex.jarvi.local
  organization:
  - Kubernetes API
  dnsNames:
  - dex.jarvi.local
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Certificate-dex" ) }}